name: Deploy to Vercel (disabled)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ false }} # Disabled; rely on Vercel's native GitHub integration or set secrets to enable
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "Vercel deployment via GitHub Action is disabled. Use Vercel's GitHub integration or provide required secrets."